[package]
name = "test-aws-lambda-container"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.1", features = ["macros"] }
lambda_runtime = "0.13.0"
aws_lambda_events = "0.16.0"
